INSERT INTO "Tours" ("Image", "Type", "Title", "Duration", "Cost", "Reviews", "Destination")
VALUES
('../images/savoey.png', 'Food & Markets', 'Savoey Seafood Restaurant', '0-3 hours', '$25.00', 320, 'Thailand'),
('../images/railay.png', 'Beaches & Relaxation', 'Railay Beach', 'Full day (7+ hours)', '$10.00', 450, 'Thailand'),
('../images/elephJung.png', 'Adventure', 'Elephant Jungle Sanctuary Phuket', '3-5 hours', '$80.00', 600, 'Thailand'),
('../images/watArun.png', 'Culture & Temples', 'Wat Arun', '0-3 hours', '$5.00', 700, 'Thailand'),
('../images/phangNga.jpg', 'Beaches & Relaxation', 'Phang Nga Bay Kayaking', '5-7 hours', '$50.00', 380, 'Thailand'),
('../images/khaoSok.jpg', 'Nature & Wildlife', 'Khao Sok National Park', 'Multi-day', '$100.00', 250, 'Thailand'),
('../images/erawan.jpg', 'Hidden Gems', 'Erawan Waterfalls', 'Full day (7+ hours)', '$15.00', 300, 'Thailand'),
('../images/chatuchak.jpg', 'Food & Markets', 'Chatuchak Weekend Market', '3-5 hours', '$10.00', 500, 'Thailand'),
('../images/nusaDua.jpg', 'Beaches & Relaxation', 'Nusa Dua Beach', 'Full day (7+ hours)', '$15.00', 380, 'Bali'),
('../images/locavore.jpg', 'Food & Markets', 'Locavore NXT Ubud', '3-5 hours', '$120.00', 250, 'Bali'),
('../images/uluwatu.jpg', 'Culture & Temples', 'Uluwatu Temple', '0-3 hours', '$5.00', 520, 'Bali'),
('../images/batur.jpg', 'Adventure', 'Mount Batur Sunrise Trek', '5-7 hours', '$40.00', 450, 'Bali'),
('../images/sanur.jpg', 'Beaches & Relaxation', 'Sanur Beach Snorkeling', '3-5 hours', '$30.00', 300, 'Bali'),
('../images/ubud.jpg', 'Nature & Wildlife', 'Ubud Monkey Forest', '0-3 hours', '$10.00', 600, 'Bali'),
('../images/sekumpul.jpg', 'Hidden Gems', 'Sekumpul Waterfall', 'Full day (7+ hours)', '$20.00', 200, 'Bali'),
('../images/jimbaran.jpg', 'Beaches & Relaxation', 'Jimbaran Bay', 'Full day (7+ hours)', '$15.00', 350, 'Bali'),
('../images/bemaraha.jpg', 'Nature & Wildlife', 'Tsingy de Bemaraha National Park', 'Full day (7+ hours)', '$40.00', 180, 'Madagascar'),
('../images/nosyBe.jpg', 'Beaches & Relaxation', 'Nosy Be Island', 'Multi-day', '$50.00', 300, 'Madagascar'),
('../images/Andringitra.jpg', 'Adventure', 'Andringitra National Park Trek', 'Multi-day', '$70.00', 150, 'Madagascar'),
('../images/avenue.jpg', 'Nature & Wildlife', 'Avenue of the Baobabs', '0-3 hours', '$5.00', 400, 'Madagascar'),
('../images/sainteMarie.jpg', 'Beaches & Relaxation', 'Sainte Marie Island Whale Watching', '3-5 hours', '$60.00', 220, 'Madagascar'),
('../images/isalo.jpg', 'Hidden Gems', 'Isalo National Park', 'Full day (7+ hours)', '$35.00', 250, 'Madagascar'),
('../images/ifaty.jpg', 'Beaches & Relaxation', 'Ifaty Beach', 'Full day (7+ hours)', '$20.00', 180, 'Madagascar'),
('../images/Ranomafana.jpg', 'Nature & Wildlife', 'Ranomafana National Park', '5-7 hours', '$45.00', 200, 'Madagascar');
