version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=TourDb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - tour-network

  pgadmin:
    image: dpage/pgadmin4:8.0
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=adminpassword
    ports:
      - "8082:80"
    depends_on:
      - db
    networks:
      - tour-network

  app:
    build:
      context: .
      dockerfile: TourAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=TourDb;Username=postgres;Password=mysecretpassword
    ports:
      - "5110:80"
    depends_on:
      - db
    networks:
      - tour-network

  migrations:
    build:
      context: .
      dockerfile: TourAPI/Dockerfile
    command: ["dotnet", "ef", "database", "update"]
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=TourDb;Username=postgres;Password=mysecretpassword
    depends_on:
      - db
    networks:
      - tour-network

networks:
  tour-network:
    driver: bridge

volumes:
  postgres-data:
